-- Common CODO rules catalog (global, shared across projects)
CREATE TABLE IF NOT EXISTS `codo_common_rules` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phase` ENUM('developer','tester','project') NOT NULL,
  `rule_key` VARCHAR(64) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `subtitle` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` VARCHAR(36) NULL DEFAULT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_codo_common_phase_key` (`phase`, `rule_key`),
  KEY `idx_codo_common_phase_active` (`phase`, `is_active`),
  KEY `idx_codo_common_sort` (`phase`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Seed developer rules (25) — Master SOP v2.0 Requirement text
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_1', 'Hard State Reset', 'Rule 1', 'Reset components cleanly on form submission and modal unmount (useEffect cleanup). Old inputs must never bleed into next entries.\n\nMalayalam: ഫോം സബ്മിറ്റ് ചെയ്താലോ മോഡൽ ക്ലോസ് ചെയ്താലോ ഫീൽഡുകൾ പൂർണ്ണമായും ക്ലിയർ ചെയ്യണം.', 1, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_2', 'Real-Time Input Validation', 'Rule 2', 'Execute inline validation feedback dynamically before form submission.\n\nMalayalam: യൂസർ സബ്മിറ്റ് ചെയ്യുന്നതിന് മുൻപ് തന്നെ ഇൻലൈൻ എറർ ഫീഡ്ബാക്ക് കാണിക്കണം.', 2, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_3', 'Persistent Input Protection', 'Rule 3', 'Intercept backdrop clicks or page navigation if form is dirty with an Unsaved Changes warning.\n\nMalayalam: ഫോം പൂരിപ്പിക്കുന്നതിനിടയിൽ മാറിയാൽ Unsaved Changes വാണിംഗ് കാണിക്കണം.', 3, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_4', 'Data-Clear Verification', 'Rule 4', 'Never rely on native browser cache for resetting inputs; explicitly wipe local state arrays upon cancel/submit.', 4, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_5', 'Numeric Character Constraints', 'Rule 5', 'Hard-clamp phone numbers and national IDs (maxLength=10 or 15). Prevent typing infinite numbers.\n\nMalayalam: ഫോൺ നമ്പറുകൾ 10 ഡിജിറ്റിൽ കൂടുതൽ ടൈപ്പ് ചെയ്യാൻ അനുവദിക്കരുത്.', 5, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_6', 'Sanitization Defenses', 'Rule 6', 'Escape and validate inputs on both Frontend and Backend to block SQLi and XSS (script injection).', 6, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_7', 'Length Guardrails', 'Rule 7', 'Provide frontend validation masks matching backend database column constraints.', 7, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_8', 'Anti-Double Click Lockout', 'Rule 8', 'Disable action buttons instantly on click and display a loading spinner.\n\nMalayalam: ക്ലിക്ക് ചെയ്ത ഉടൻ ബട്ടൺ ഡിസേബിൾ ആയി സ്പിന്നർ കാണിക്കണം.', 8, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_9', 'Mandatory Deletion Gating', 'Rule 9', 'Never run destructive API calls directly. Require a Small (400px) confirmation modal.\n\nMalayalam: Delete അമർത്തുമ്പോൾ 400px കൺഫർമേഷൻ മോഡൽ വഴി അനുമതി വാങ്ങിയിരിക്കണം.', 9, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_10', 'Submit Button Lock', 'Rule 10', 'Disable the submit button until all required field validations evaluate to true.', 10, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_11', 'The Codo Corner', 'Rule 11', 'All UI containers, buttons, and cards MUST use rounded-xl (12px) or rounded-2xl (16px). Sharp edges are forbidden.', 11, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_12', '12-Column Grid Alignment', 'Rule 12', 'Layouts must conform to a 12-column grid system with explicit gap-4 or gap-6 spacing.', 12, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_13', 'Whitespace Isolation', 'Rule 13', 'Never declare dynamic spacing utilities (mb-X, pb-X) inside .map() array loops. Use parent grid/flex gap properties.', 13, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_14', 'Viewport Scroll Defenses', 'Rule 14', 'Never apply global overflow: hidden on the root body. Implement Codo''s custom slim scrollbar styles.', 14, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_15', 'Theme Integrity', 'Rule 15', 'Test every background/text utility to ensure seamless contrast scaling across Dark Mode and Light Mode.', 15, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_16', 'Bidirectional Text Safety', 'Rule 16', 'Multi-language inputs handling Arabic must explicitly set dir="rtl" and preserve caret/number alignment.', 16, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_17', 'Custom Picker Normalization', 'Rule 17', 'Date and time pickers must handle null/undefined states cleanly and map display formatting separately from ISO payloads.', 17, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_18', 'Strict Data Sorting', 'Rule 18', 'All database query layers must include explicit ordering (ORDER BY created_at DESC). Random listing order is unacceptable.', 18, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_19', 'Skeleton Shimmer Loaders', 'Rule 19', 'Never render a blank screen or plain text spinner during data fetch. Use layout-matching Skeleton Shimmers.', 19, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_20', '1.5-Second Threshold', 'Rule 20', 'Maintain main-thread execution under 1.5s via WebP images, lazy loading, asset compression, and active PWA service workers.', 20, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_21', 'Database Indexing', 'Rule 21', 'Any database column used in WHERE, JOIN, ORDER BY, or GROUP BY must be explicitly indexed.', 21, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_22', 'High-Volume Scale', 'Rule 22', 'Tables expecting more than 100 entries must implement server-side Pagination or Infinite Scroll bounds.', 22, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_23', 'Console Scrubbing', 'Rule 23', 'Strip all console.log(), print(), or dd() debug statements before pushing or planning output.', 23, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_24', 'Secret Variable Isolation', 'Rule 24', 'All API keys and secrets must reside strictly in .env and be excluded via .gitignore.', 24, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_25', 'Documentation Mandate', 'Rule 25', 'Write explicit JSDoc/PHPDoc explaining the Why behind complex helper functions and business logic.', 25, 1);

-- Seed tester / QA stress rules (7)
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_apple_sandbox', 'The Apple Ecosystem Sandbox', 'QA Stress 1', 'Test cross-platform layout rendering across Safari environments. Confirm layout structures, card radii, and shadow boundaries scale without breaking.', 1, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_click_attack', 'The Click Attack Safeguard', 'QA Stress 2', 'Stress-test button structures via continuous high-speed double and triple clicks. Ensure execution locks prevent duplicate API records.', 2, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_theme_interruption', 'The Theme Interruption Matrix', 'QA Stress 3', 'Change interface color styles rapidly back and forth mid-form to detect and address unreadable text variables.', 3, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_input_interception', 'The Input Interception Prompt', 'QA Stress 4', 'Open form modals, alter form field strings, and simulate a layout close command. Verify warning safeguards capture user context safely.', 4, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_empty_array', 'The Empty Array Fallback', 'QA Stress 5', 'Simulate empty or empty-result states across relational data blocks. Confirm descriptive empty placeholder messaging handles the viewport safely.', 5, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_boundary_expansion', 'The Boundary Expansion Constraint', 'QA Stress 6', 'Attempt long string pastes (100+ digit entries) in phone inputs. Confirm truncation rules drop unnecessary data inputs seamlessly.', 6, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_network_break', 'The Network Break Strategy', 'QA Stress 7', 'Drop network visibility mid-action or check server error routing. Confirm immediate user notifications via interactive Toast alerts.', 7, 1);
