-- Common CODO rules catalog (global, shared across projects)
CREATE TABLE IF NOT EXISTS `codo_common_rules` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phase` ENUM('developer','tester','project') NOT NULL,
  `rule_key` VARCHAR(64) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `subtitle` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` VARCHAR(36) NULL DEFAULT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_codo_common_phase_key` (`phase`, `rule_key`),
  KEY `idx_codo_common_phase_active` (`phase`, `is_active`),
  KEY `idx_codo_common_sort` (`phase`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Seed developer rules (25)
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_1', 'Hard State Reset', 'Rule 1', 'Reset components cleanly on form submit and modal unmount (useEffect cleanup phase).', 1, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_2', 'Real-Time Input Validation', 'Rule 2', 'Inline validation messages must execute before submission triggers.', 2, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_3', 'Persistent Input Protection', 'Rule 3', 'Trigger an Unsaved Changes warning if a user exits an active mid-form.', 3, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_4', 'Data-Clear Verification', 'Rule 4', 'Completely clear local arrays on successful save or manual cancel. Do not depend on browser engine defaults.', 4, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_5', 'Numeric Character Constraints', 'Rule 5', 'Enforce rigid max string clamping on telephone numbers (maxLength={10} or maxLength={15} for international scopes).', 5, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_6', 'Sanitization Defenses', 'Rule 6', 'Enforce strict type validation arrays and escape scripts on both front and backend entry lanes to block malicious injections.', 6, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_7', 'Length Guardrails', 'Rule 7', 'Maintain backend size limits alongside frontend validation inputs to completely prevent engine exceptions.', 7, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_8', 'Anti-Double Click Lockout', 'Rule 8', 'Buttons must implement an immediate loading state spinner and switch to disabled state instantly on click #1.', 8, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_9', 'Mandatory Deletion Gating', 'Rule 9', 'No entity removals allowed directly. Destructive operations require a Small 400px authorization confirmation block.', 9, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_10', 'Submit Button Lock', 'Rule 10', 'Enforce dynamic programmatic locking on primary submission actions until fields pass local evaluations.', 10, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_11', 'The Codo Corner', 'Rule 11', 'Apply a uniform 12px to 16px curve boundary on cards, blocks, overlays, and button interfaces.', 11, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_12', '12-Column Grid Alignment', 'Rule 12', 'Desktop interface viewports must scale along a uniform 12-column framework using gap-4 or gap-6 white-spacing parameters.', 12, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_13', 'Whitespace Isolation', 'Rule 13', 'Keep layout files clear of whitespace bloat; avoid appending margins (mb-X, pb-X) dynamically inside nested iterative layout arrays.', 13, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_14', 'Viewport Scroll Defenses', 'Rule 14', 'Do not declare absolute overflow constraints (overflow: hidden) globally across standard views. Preserve Codo slim scroll styling.', 14, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_15', 'Theme Integrity', 'Rule 15', 'Verify complete text contrast clarity across active components when rapidly toggling between dark and light templates.', 15, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_16', 'Bidirectional Text Safety', 'Rule 16', 'Form elements must flawlessly handle RTL alignment matrices (dir="rtl") when parsing localized Arabic text layouts without scrambling indices.', 16, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_17', 'Custom Picker Normalization', 'Rule 17', 'Separate display logic cleanly from state management inputs within custom calendar or selector tools; handle empty values without unexpected application breaks.', 17, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_18', 'Strict Data Sorting', 'Rule 18', 'Relational dashboards and index tables must explicitly incorporate server-side order rules (ORDER BY created_at DESC) to ensure data layout clarity.', 18, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_19', 'Skeleton Shimmer Loaders', 'Rule 19', 'White outs or plain loading views are banned; implement flickering shimmer shells that map closely to incoming content structures.', 19, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_20', 'The 1.5-Second Threshold', 'Rule 20', 'Streamline operational execution paths to complete initial render in under 1.5 seconds via image optimization (WebP) and functional PWA service caching.', 20, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_21', 'Database Indexing', 'Rule 21', 'Confirm search keys, matching indices, and query-heavy filters link straight to optimized column structures within the data schema.', 21, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_22', 'High-Volume Scale', 'Rule 22', 'Implement server-managed page boundaries or robust infinite-scroll loops on modules surpassing 100 historical data row entries.', 22, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_23', 'Console Scrubbing', 'Rule 23', 'Ensure code logic is cleared of debug logs (console.log(), print(), dd()) prior to running production deployment builds.', 23, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_24', 'Secret Variable Isolation', 'Rule 24', 'Move API tokens, merchant gateway profiles, and security files safely out of local code and into isolated .env configurations.', 24, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('developer', 'dev_rule_25', 'Documentation Mandate', 'Rule 25', 'Enforce descriptive JSDoc / PHPDoc standard summaries clarifying the exact architectural reasoning behind non-trivial helpers or data operations.', 25, 1);

-- Seed tester / QA stress rules (7)
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_apple_sandbox', 'The Apple Ecosystem Sandbox', 'QA Stress 1', 'Test cross-platform layout rendering across Safari environments. Confirm layout structures, card radii, and shadow boundaries scale without breaking.', 1, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_click_attack', 'The Click Attack Safeguard', 'QA Stress 2', 'Stress-test button structures via continuous high-speed double and triple clicks. Ensure execution locks prevent duplicate API records.', 2, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_theme_interruption', 'The Theme Interruption Matrix', 'QA Stress 3', 'Change interface color styles rapidly back and forth mid-form to detect and address unreadable text variables.', 3, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_input_interception', 'The Input Interception Prompt', 'QA Stress 4', 'Open form modals, alter form field strings, and simulate a layout close command. Verify warning safeguards capture user context safely.', 4, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_empty_array', 'The Empty Array Fallback', 'QA Stress 5', 'Simulate empty or empty-result states across relational data blocks. Confirm descriptive empty placeholder messaging handles the viewport safely.', 5, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_boundary_expansion', 'The Boundary Expansion Constraint', 'QA Stress 6', 'Attempt long string pastes (100+ digit entries) in phone inputs. Confirm truncation rules drop unnecessary data inputs seamlessly.', 6, 1);
INSERT IGNORE INTO `codo_common_rules` (`phase`, `rule_key`, `title`, `subtitle`, `description`, `sort_order`, `is_active`) VALUES ('tester', 'qa_network_break', 'The Network Break Strategy', 'QA Stress 7', 'Drop network visibility mid-action or check server error routing. Confirm immediate user notifications via interactive Toast alerts.', 7, 1);
